import type { AntdStylePxToRemOptions } from "./types"

export const defaultOptions: Required<AntdStylePxToRemOptions> = {
	rootValue: 16,
	unitPrecision: 5,
	minPixelValue: 0,
	propList: ["*"],
	selectorBlackList: [],
	replace: true,
	mediaQuery: false,
	include: undefined!,
	exclude: undefined!,
	cssTemplateFunctions: ["css"],
	enableJSXTransform: true,
	jsxAttributeMapping: {},
}

export const lengthProperties = new Set([
	"width",
	"height",
	"minWidth",
	"minHeight",
	"maxWidth",
	"maxHeight",
	"padding",
	"paddingTop",
	"paddingRight",
	"paddingBottom",
	"paddingLeft",
	"margin",
	"marginTop",
	"marginRight",
	"marginBottom",
	"marginLeft",
	"left",
	"right",
	"top",
	"bottom",
	"fontSize",
	"lineHeight",
	"borderRadius",
	"borderTopLeftRadius",
	"borderTopRightRadius",
	"borderBottomLeftRadius",
	"borderBottomRightRadius",
	"borderWidth",
	"borderTopWidth",
	"borderRightWidth",
	"borderBottomWidth",
	"borderLeftWidth",
	"gap",
	"rowGap",
	"columnGap",
	"flexBasis",
	"outlineWidth",
	"letterSpacing",
	"wordSpacing",
])
